import z from '@deepseek-ai/schemastery';
// 1.8.2: MAX_TIMER_DELAY_MS used to come from `@deepseek-ai/dsh-timeout` as a
// static import — a host peer whose export list can change at any rc release.
// Owning the constant here keeps the config schema loadable on any host.
import { MAX_TIMER_DELAY_MS } from './compat/timing.js';
/**
 * Loader schema: validates configuration and fills defaults at plugin load.
 * Invalid configuration fails the load loudly (harness convention).
 */
export const Config = z.object({
    temperature: z.number().min(0).max(2).default(0.2),
    maxTokens: z.number().step(1).min(1).max(128000).default(1200),
    maxRetries: z.number().step(1).min(0).max(5).default(1),
    maxCalls: z.number().step(1).min(1).max(20).default(4),
    maxInputChars: z.number().step(1).min(1).max(100000).default(4000),
    maxInputTokens: z.number().step(1).min(0).max(200000).default(3000),
    timeoutMs: z.number().step(1).min(1).max(MAX_TIMER_DELAY_MS).default(60000),
    outputLanguage: z.string().default('auto'),
    outputStyle: z.union(['sections', 'plain', 'role-task-goal']).default('plain'),
    metaPromptLanguage: z.union(['auto', '中文', '英文']).default('auto'),
    autoOptimize: z.boolean().default(true),
    autoOptimizePrefix: z.string().default('/optimize '),
    extraInstructions: z.string(),
    examples: z.array(z.object({
        input: z.string().required(),
        output: z.string().required(),
    })),
    minSectionChars: z.number().step(1).min(0).max(10000).default(10),
    maxTokenRetryFactor: z.number().min(1).max(3).default(1.5),
    maxTokensCap: z.number().step(1).min(1).max(128000).default(8000),
    maxTotalTokens: z.number().step(1).min(0).default(20000),
    retryTemperatureStep: z.number().min(0).max(2).default(0.3),
    skipIfAlreadyOptimized: z.boolean().default(true),
    selfRefine: z.boolean().default(false),
    autoOptimizeAll: z.boolean().default(false),
    hookIncludeOriginal: z.boolean().default(false),
    cacheEnabled: z.boolean().default(true),
    cacheMaxEntries: z.number().step(1).min(0).max(10000).default(200),
    cacheTtlMs: z.number().step(1).min(0).max(MAX_TIMER_DELAY_MS).default(600000),
    cacheFuzzyMatch: z.boolean().default(true),
    cacheFuzzyThreshold: z.number().min(0).max(1).default(0.6),
    senseNeeds: z.boolean().default(false),
    contextAware: z.boolean().default(true),
    contextMaxMessages: z.number().step(1).min(0).max(100).default(10),
    contextMaxTokens: z.number().step(1).min(0).max(200000).default(800),
    outputLengthMaxTokens: z.number().step(1).min(0).max(200000).default(800),
    situationProfileLevel: z.union(['off', 'minimal', 'full']).default('full'),
    goalAlignmentRetry: z.boolean().default(true),
    optimizationProfile: z.union(['balanced', 'fast']).default('balanced'),
    earlyStop: z.boolean().default(false),
    builtinExamples: z.boolean().default(true),
    sceneRefEnabled: z.boolean().default(true),
    classifier: z.union(['heuristic', 'llm']).default('heuristic'),
    localTemplate: z.union(['on', 'off', 'hybrid']).default('off'),
    hybridAlignThreshold: z.number().min(0).max(1).default(0.4),
    templateId: z.string().default('default'),
    metaPromptTemplate: z.object({
        optimizeZh: z.string(),
        optimizeEn: z.string(),
        iterateZh: z.string(),
        iterateEn: z.string(),
    }),
    provider: z.string(),
    model: z.string(),
    earlyStopTailChunks: z.number().step(1).min(1).max(100).default(16),
    earlyStopTailGrowth: z.number().step(1).min(1).max(200).default(24),
    autoAdapt: z.boolean().default(true),
    minAdaptEpisodes: z.number().step(1).min(5).max(100).default(10),
    persistState: z.boolean().default(true),
    stateFile: z.string().required(false),
});
